### ISSUE TITLE
Problem with  select_by_key when called twice with the same argument

### ISSUE THREAD

**Issue by dputhier** [dputhier/libgtftk#16]
It seems that when select_by_key is called twice with the same parameters it leads to a segfault:

       from  gtftk.utils import get_example_file
       from gtftk.gtf_interface import GTF 
       a_file = get_example_file()[0]
       gtf = GTF(a_file)
       a = gtf.select_by_key("feature", "transcript")
       b = a.select_by_key("feature", "transcript")
       Segmentation fault: 11

       from  gtftk.utils import get_example_file
       from gtftk.gtf_interface import GTF 
       a_file = get_example_file()[0]
       gtf = GTF(a_file)
       a = gtf.select_by_key("feature", "gene").select_by_key("feature", "gene")
       Segmentation fault: 11

**Comment by fafa13** [comment]
I know why. The first time the function is called, an index on feature 
column is made. When the function is called a second time, the index is 
not rebuilt because it already exists but it doesn't correspond to the 
gtf_data with which the function is called the second time. That's why I 
rebuilt the index each time the function was called but now we know that 
it's not a good way to solve the problem. I think I have to change the 
column model ...

**Comment by dputhier** [comment]
Just note that this seems to be associated with some particular index:

         from  gtftk.utils import get_example_file
         from gtftk.gtf_interface import GTF
         from gtftk.utils import TAB
         a_file = get_example_file()[0]
         gtf = GTF(a_file)

This line works

         a = gtf.select_by_key("gene_id", "G0001").select_by_key("gene_id", "G0001")

This line won't

        a = gtf.select_by_key("feature", "transcript").select_by_key("feature", "transcript")
        Segmentation fault: 11

**Comment by fafa13** [comment]
You're lucky for the first test, maybe because you dataset is small. 
With a real gene_id and the whole human GTF, it doesn't work.

**Comment by dputhier** [comment]
Fixed.
